-- Smart Production Linie mit 4 Maschinen
DROP DATABASE MES;

CREATE DATABASE IF NOT EXISTS MES;

CREATE TABLE IF NOT EXISTS MES.MACHINES (
    MACHINE_ID SMALLINT(5) UNSIGNED NOT NULL,
    NAME VARCHAR(45) NOT NULL,
    NAME_PARA1 VARCHAR(45),
    NAME_PARA2 VARCHAR(45),
    PRIMARY KEY (MACHINE_ID)
);

CREATE TABLE IF NOT EXISTS MES.VARIANTS (
    VARIANT_ID SMALLINT(5) UNSIGNED NOT NULL,
    NAME VARCHAR(45) NOT NULL,
    PRIMARY KEY (VARIANT_ID)
);

CREATE TABLE IF NOT EXISTS MES.PRODUCTION_STEPS (
    PRODUCTION_STEP_ID SMALLINT(5) UNSIGNED NOT NULL,
    STEP_NO SMALLINT(5) UNSIGNED NOT NULL,
    VARIANT_ID SMALLINT(5) UNSIGNED NOT NULL,
    MACHINE_ID SMALLINT(5) UNSIGNED NOT NULL,
    PARA1 SMALLINT(5),
    PARA2 SMALLINT(5),
    PRIMARY KEY (PRODUCTION_STEP_ID)
);

CREATE TABLE IF NOT EXISTS MES.PRODUCTS (
    PRODUCT_ID SMALLINT(5) UNSIGNED NOT NULL,
    NAME VARCHAR(45) NOT NULL,
    PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS MES.COLORS (
    COLOR_ID SMALLINT(5) UNSIGNED NOT NULL,
    WEB_COLOR VARCHAR(7) NOT NULL,
    NAME VARCHAR(45) NOT NULL,
    PRIMARY KEY (COLOR_ID)
);

CREATE TABLE IF NOT EXISTS MES.CUSTOMERS (
    CUSTOMER_ID SMALLINT(5) UNSIGNED NOT NULL,
    NAME VARCHAR(45) NOT NULL,
    CONTACT VARCHAR(45) NOT NULL,
    STREET VARCHAR(45) NOT NULL,
    ZIP VARCHAR(45) NOT NULL,
    CITY VARCHAR(45) NOT NULL,
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS MES.PARTS (
    PART_ID SMALLINT(5) UNSIGNED NOT NULL,
    RFID SMALLINT(5),
    COLOR_ID SMALLINT(5) UNSIGNED NOT NULL,
    PART_STATE SMALLINT(5),
    PRIMARY KEY (PART_ID)
);

CREATE TABLE IF NOT EXISTS MES.STOCKYARDS (
    STOCKYARD_ID SMALLINT(5) UNSIGNED NOT NULL,
    PART_ID SMALLINT(5),
    PRIMARY KEY (STOCKYARD_ID)
);

CREATE TABLE IF NOT EXISTS MES.ORDERS (
    ORDER_ID SMALLINT(5) UNSIGNED NOT NULL,
    PRODUCT_ID SMALLINT(5) UNSIGNED NOT NULL,
    COLOR_ID  SMALLINT(5) UNSIGNED NOT NULL,
    VARIANT_ID SMALLINT(5) UNSIGNED NOT NULL,
    CUSTOMER_ID SMALLINT(5) UNSIGNED NOT NULL,
    ORDER_STATE SMALLINT(5),
    PART_ID SMALLINT(5) UNSIGNED,
    PRIMARY KEY (ORDER_ID)
);

CREATE TABLE IF NOT EXISTS MES.PROD_DATA (
    LOG_TIME TIMESTAMP NOT NULL,
    LOG_TYPE SMALLINT(5),
    RFID SMALLINT(5),
    MACHINE SMALLINT(5),
    DURATION BIGINT UNSIGNED,
    MESSAGE VARCHAR(160) NOT NULL
);

INSERT INTO MES.MACHINES (MACHINE_ID, NAME, NAME_PARA1, NAME_PARA2) VALUES (1, 'Lager', 'Lagerplatz', '');
INSERT INTO MES.MACHINES (MACHINE_ID, NAME, NAME_PARA1, NAME_PARA2) VALUES (2, 'Wenden', '', '');
INSERT INTO MES.MACHINES (MACHINE_ID, NAME, NAME_PARA1, NAME_PARA2) VALUES (3, 'Drucker', 'Layout', '');
INSERT INTO MES.MACHINES (MACHINE_ID, NAME, NAME_PARA1, NAME_PARA2) VALUES (4, 'Ofen', 'Temperatur', 'Trockenzeit');

INSERT INTO MES.COLORS (COLOR_ID, WEB_COLOR, NAME) VALUES (1, '#00FFFF', 'blau');
INSERT INTO MES.COLORS (COLOR_ID, WEB_COLOR, NAME) VALUES (2, '#FF0000', 'rot');
INSERT INTO MES.COLORS (COLOR_ID, WEB_COLOR, NAME) VALUES (3, '#FFFF00', 'gelb');


INSERT INTO MES.STOCKYARDS (STOCKYARD_ID, PART_ID) VALUES (1, 0);
INSERT INTO MES.STOCKYARDS (STOCKYARD_ID, PART_ID) VALUES (2, 0);
INSERT INTO MES.STOCKYARDS (STOCKYARD_ID, PART_ID) VALUES (3, 0);
INSERT INTO MES.STOCKYARDS (STOCKYARD_ID, PART_ID) VALUES (4, 0);
INSERT INTO MES.STOCKYARDS (STOCKYARD_ID, PART_ID) VALUES (5, 0);
INSERT INTO MES.STOCKYARDS (STOCKYARD_ID, PART_ID) VALUES (6, 0);

INSERT INTO MES.PRODUCTS (PRODUCT_ID, NAME) VALUES (1, 'Fahrradcomputer');

INSERT INTO MES.CUSTOMERS (CUSTOMER_ID, NAME, CONTACT, STREET, ZIP, CITY) VALUES (1, 'Ostseerad e. K.', 'Simon Fischer', 'Am Stadtwald 15', '17389', 'Anklam');
INSERT INTO MES.CUSTOMERS (CUSTOMER_ID, NAME, CONTACT, STREET, ZIP, CITY) VALUES (2, 'Rädleland e. K. ', 'Levi Schiller', 'Hambacher Straße 59', '70825 ', 'Stuttgart');
INSERT INTO MES.CUSTOMERS (CUSTOMER_ID, NAME, CONTACT, STREET, ZIP, CITY) VALUES (3, 'Bavaria Bikes', 'Karin Klinger', 'Rappenweg 23', '92275', 'München');
INSERT INTO MES.CUSTOMERS (CUSTOMER_ID, NAME, CONTACT, STREET, ZIP, CITY) VALUES (4, 'Neckarad GmbH', 'Senad Yalzin', 'Blumenthalstraße 87', '69115', 'Heidelberg');
INSERT INTO MES.CUSTOMERS (CUSTOMER_ID, NAME, CONTACT, STREET, ZIP, CITY) VALUES (5, 'Drahtesel', 'Theresa Zerr', 'Ecksteinstraße 15', '04277', 'Leipzig');
INSERT INTO MES.CUSTOMERS (CUSTOMER_ID, NAME, CONTACT, STREET, ZIP, CITY) VALUES (6, 'Capital Bikes OHG', 'James Smith', 'Reichenberger Straße 2', '16341', 'Berlin');
INSERT INTO MES.CUSTOMERS (CUSTOMER_ID, NAME, CONTACT, STREET, ZIP, CITY) VALUES (7, 'Alster Cycling', 'Fabian Maier', 'Loogestieg 50', '22760', 'Hamburg');
INSERT INTO MES.CUSTOMERS (CUSTOMER_ID, NAME, CONTACT, STREET, ZIP, CITY) VALUES (8, 'Red Light Bikes', 'Chris Adomat', 'Mörkenstraße 42', '22767', 'Hamburg');
INSERT INTO MES.CUSTOMERS (CUSTOMER_ID, NAME, CONTACT, STREET, ZIP, CITY) VALUES (9, 'Cruiser Bikes', 'Alina Steck', 'Nienhagener Straße 31-33', '30627', 'Hannover');
INSERT INTO MES.CUSTOMERS (CUSTOMER_ID, NAME, CONTACT, STREET, ZIP, CITY) VALUES (10, 'VeloDOM', 'Vanessa Pschorn', 'Am Hansehafen 5', '39130', 'Magdeburg');
INSERT INTO MES.CUSTOMERS (CUSTOMER_ID, NAME, CONTACT, STREET, ZIP, CITY) VALUES (11, 'FahrPott', 'Luca Dähmel', 'Stiepler Straße 64', '44784', 'Bochum');
INSERT INTO MES.CUSTOMERS (CUSTOMER_ID, NAME, CONTACT, STREET, ZIP, CITY) VALUES (12, 'Fahrrad Glocke GmbH', 'Selin Gönül', 'Mittelstraße 55', '50672', 'Köln');
INSERT INTO MES.CUSTOMERS (CUSTOMER_ID, NAME, CONTACT, STREET, ZIP, CITY) VALUES (13, 'Airport Bikes', 'David Müller', 'Im Schwalbennest 10', '60549', 'Frankfurt');
INSERT INTO MES.CUSTOMERS (CUSTOMER_ID, NAME, CONTACT, STREET, ZIP, CITY) VALUES (14, 'Fahrradmarkt Heidelberg GmbH', 'Jasmin Ütztürk', 'Hauptstraße 11', '69115', 'Heidelberg');
INSERT INTO MES.CUSTOMERS (CUSTOMER_ID, NAME, CONTACT, STREET, ZIP, CITY) VALUES (15, 'Schmitts Radladen KG', 'Robin Schmitt', 'Philosophenweg 5', '69120', 'Heidelberg');
INSERT INTO MES.CUSTOMERS (CUSTOMER_ID, NAME, CONTACT, STREET, ZIP, CITY) VALUES (16, 'Simon Hugendubel', 'Simon Hugendubel', 'Röhrer Höhe 73', '70599', 'Stuttgart');
INSERT INTO MES.CUSTOMERS (CUSTOMER_ID, NAME, CONTACT, STREET, ZIP, CITY) VALUES (17, 'Bike-Center Raidling GmbH', 'Lara Kruft', 'Münstergasse 17', '79111', 'Freiburg');
INSERT INTO MES.CUSTOMERS (CUSTOMER_ID, NAME, CONTACT, STREET, ZIP, CITY) VALUES (18, 'Fahrradmarkt Müller e. K.', 'Martin Müller', 'Haldenstraße 78', '85579', 'Neubiberg');


INSERT INTO MES.VARIANTS (VARIANT_ID, NAME) VALUES (1, 'Rückseite mit Motiv 1 bedrucken');
INSERT INTO MES.VARIANTS (VARIANT_ID, NAME) VALUES (2, 'Rückseite mit Motiv 2 bedrucken');
INSERT INTO MES.VARIANTS (VARIANT_ID, NAME) VALUES (3, 'Rückseite mit Motiv 3 bedrucken');
INSERT INTO MES.VARIANTS (VARIANT_ID, NAME) VALUES (4, 'Vorderseite mit Motiv 1 bedrucken');
INSERT INTO MES.VARIANTS (VARIANT_ID, NAME) VALUES (5, 'Vorderseite mit Motiv 2 bedrucken');
INSERT INTO MES.VARIANTS (VARIANT_ID, NAME) VALUES (6, 'Vorderseite mit Motiv 3 bedrucken');


CREATE VIEW MES.DATA_ANALYSIS AS 
SELECT  
	pd.LOG_TIME,
	pd.LOG_TYPE,
	pd.RFID,
	pd.MACHINE,
	pd.DURATION,
	pd.MESSAGE,
	o.ORDER_ID,
	p.COLOR_ID,
	c.NAME AS COLOR_NAME,
	cu.NAME AS CUST_NAME,
	cu.CONTACT,
	cu.STREET,
	cu.ZIP,
	cu.CITY,
	v.NAME AS VAR_NAME,
	m.NAME AS MACHINE_NAME
FROM
    MES.PROD_DATA pd
        INNER JOIN
    MES.PARTS p ON p.RFID = pd.RFID
        INNER JOIN
    MES.COLORS c ON c.COLOR_ID = p.COLOR_ID
        INNER JOIN
    MES.ORDERS o ON o.PART_ID = p.PART_ID
        INNER JOIN
    MES.VARIANTS v ON v.VARIANT_ID = o.VARIANT_ID
        INNER JOIN
    MES.CUSTOMERS cu ON cu.CUSTOMER_ID = o.CUSTOMER_ID
        INNER JOIN
    MES.MACHINES m ON m.MACHINE_ID = pd.MACHINE;